# Experiment settings

# Experiment repository
experiment_repo: "geometry-based-wireless-power-transfer"  # github repo name
organisation: "techtile-by-dramco"  # github org

# Server settings
server:
  host: "techtile-geof.local"
  messaging_port: 5678
  sync_port: 5679
heartbeat_interval: 10

# Tile settings
#tiles: "segmentB segmentF"
#tiles: "D06"    # group name, single tile, or space-separated list
#tiles: "A05 A06 A07 A08 A09 A10"    # group name, single tile, or space-separated list

extra_packages:                     # list of extra packages to be installed on the tiles' rpi's
  - python3-numpy
  - python3-scipy
  - python3-zmq

# Name of the script to run on the clients (make sure it is in the <your-repo>/client folder)
client_script_name: "run_client.py"
client_script_args:
  - "--config-file"
  - "/home/pi/geometry-based-wireless-power-transfer/experiment-settings.yaml"

# Server script behaviour
test_connectivity: False             # set True if you want to test tile connectivity before continuing.
halt_on_connectivity_failure: False  # set False if you want to continue with only the active tiles
